name: run the ntpel

on:
  schedule:
    - cron: '0 8 * * *' # every day at 8 AM UTC
  workflow_dispatch:     # allow manual trigger

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Git user
        run: |
          git config --global user.name "ruddhirani"
          git config --global user.email "nruddhi@gmail.com"

      - name: Fixing Bug
        run: |
          echo "Green tick done" >> activity.log
          git add activity.log
          git commit -m "fixing bug" || echo "No changes to commit"
          git push
